# Instructions

The places where you have enter code, to answer the questions, are marked with `# YOUR CODE HERE`.


## Question 1 (3 points)

Complete the function `get_Q` that returns a $Q$ matrix for the following objective function:

$$f(x_1, x_2, x_3, x_4) = 3x_1 + 2x_2 - x_3 - 4 x_4 + 2x_1x_3 - 5x_2x_4
.$$

The function `get_Q` has

- Input: None
- Returns: A numpy array representing $Q$ matrix


In [2]:
import numpy as np 

def get_Q():
    # YOUR CODE HERE
   
    Q = np.array([[ 3,  0,  2,  0],
                  [ 0,  2,  0, -5],
                  [ 0,  0, -1,  0],
                  [ 0,  0,  0, -4]])
    # Do not modify anything below this line
    return Q

In [3]:
# You can use this cell to call and check the output of the function

print(get_Q())

[[ 3  0  2  0]
 [ 0  2  0 -5]
 [ 0  0 -1  0]
 [ 0  0  0 -4]]


In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

## Question 2 (5 points)

Complete function `maximize` that takes as input a `Q` matrix and returns the **maximium** value of the corresponding objective function.

The function `maximize` has

- Input: A numpy array representing $Q$ matrix
- Returns: Maximum value of the corresponding objective function

Hint: You can use the function `qubo_solver` given below. `qubo_solver` takes as input a `Q` matrix and returns the vector of variables that **minimizes** the corresponding function. 

In [4]:
import itertools
import numpy as np

def qubo_solver(Q_matrix):
    possible_values = {}
    # A list of all the possible permutations for x vector
    vec_permutations = itertools.product([0, 1], repeat=Q_matrix.shape[0])

    for permutation in vec_permutations:
        x = np.array(
            [[var] for var in permutation]
        )  # Converts the permutation into a column vector
        value = (x.T).dot(Q_matrix).dot(x)
        possible_values[
            value[0][0]
        ] = x  # Adds the value and its vector to the dictionary

    min_value = min(possible_values.keys())  # Lowest value of the objective function
    opt_vector = tuple(
        possible_values[min_value].T[0]
    )  # Optimum vector x that produces the lowest value

    return opt_vector

In [6]:
def maximize(Q):
    # YOUR CODE HERE
    for x in itertools.product([0, 1], repeat = 4): 
        v = 3 * 𝑥[0] + 2 * 𝑥[1] - 1 * 𝑥[2] - 4 * 𝑥[3] + 2 * 𝑥[0] * 𝑥[2] - 5*𝑥[1]*𝑥[3]
     
    # Do not modify anything below this line
    return v

In [7]:
# You can use this cell to call and check the output of the function

import numpy as np

Q = np.array([[1, 1], [0, -1]])

print(maximize(Q))

-3


In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

## Question 3 (5 points)

Next questions are about the Knapsack Problem.

Given $n$ items, each with an associated weight $w_i$ and cost $c_i$, the goal of the Knapsack problem is to pack as many items to maximize the value of the packed knapsack, while not exceeding the knapsack capacity.

Let $x_i$ be a binary variable that is equal to 1 if $i$'th item is selected and 0 otherwise. 

Complete the function `objective` so that it returns a string corresponding to the objective function

$$
\max~~f(x_0,x_1,\dots,x_{n-1})
$$
for the Knapsack Problem.

The function `objective` has

- Inputs: `n`-number of items, `costs`-a list of $n$ elements corresponding to costs of the items, `weights`- a list of $n$ elements corresponding to the weights of the items, `W`-capacity of Knapsack
            
- Returns: A string representation of the objective function

**String representation:** Ex: For $f(x_0,x_1)= 2x_0-3x_0x_1+x_1$, string representation is `2x_0-3x_0x_1+1x_1`. The order of the terms is not important i.e. `-3x_0x_1+1x_1+2x_0` is valid as well.


In [8]:
def objective(n, weights, costs, W):
    # YOUR CODE HERE
    s = 2*costs[0] - 3*costs[0]*costs[1] + 1*costs[1]
    # Do not modify anything below this line
    return s

In [9]:
# You can use this cell to call and check the output of the function
n = 5
W = 10
weights = [1, 4, 8, 2, 3]
costs = [2, 7, 3, 4, 6]
print(objective(n, weights, costs, W))

-31


In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

## Question 5 (5 points)

Complete the function `constraint` so that it returns a string corresponding to the constraint for the Knapsack Problem.

The function `constraint` has

- Inputs: `n`-number of items, `costs`-a list of $n$ elements corresponding to costs of the items, `weights`- a list of $n$ elements corresponding to the weights of the items, `W`-capacity of Knapsack
            
- Returns: A string representation of the constraint

**String representation:** Ex: For constraint $1x_0+2x_2\leq9$, string representation is `1x_0+2x_2<=9`. The order of the terms is not important i.e. `2x_2+1x_0<=9` is valid as well.


In [10]:
def constraint(n, weights, costs, W):
    # YOUR CODE HERE
    s = 2 * weights[1] + 1 * weights[0]
    # Do not modify anything below this line
    return s

In [11]:
# You can use this cell to call and check the output of the function
n = 5
W = 10
weights = [1, 4, 8, 2, 3]
costs = [2, 7, 3, 4, 6]
print(constraint(n, weights, costs, W))

9


In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

In [ ]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect