<table width = "100%">
  <tr style="background-color:white;">
    <!-- QWorld Logo -->
    <td style="text-align:left;width:200px;"> 
        <a href="https://qworld.net/" target="_blank"><img src="../images/QWorld.png"> </a></td>
    <td style="text-align:right;vertical-align:bottom;font-size:16px;"> 
        Prepared by AkashNarayanan B and Özlem Salehi</td>    
</table>
<hr>

# <font color="blue"> Solutions for </font> Conversion Between Formulations

### Imports

In [1]:
import numpy as np
from dimod import BQM

<a id="Task1"></a>

### Task 1

Create a QUBO in NumPy matrix form for the following objective function and create a BQM from it.

$$f(x_1, x_2, x_3, x_4) = 3x_1 - 7x_2 + 11x_3 - x_4 + 9x_1 x_2 + x_1 x_3 + 2x_2 x_3 + 8x_3 x_4$$

### Solution

Define a NumPy matrix `Q` for the objective function.

In [2]:
Q_np = np.array([[  3,  9,  1,  0],
                 [  0, -7,  2,  0],
                 [  0,  0, 11,  8],
                 [  0,  0,  0, -1]])

Construct a BQM from the above NumPy matrix.

In [3]:
bqm_qubo_np = BQM(Q_np, "BINARY")

print(bqm_qubo_np)

BinaryQuadraticModel({0: 3.0, 1: -7.0, 2: 11.0, 3: -1.0}, {(1, 0): 9.0, (2, 0): 1.0, (2, 1): 2.0, (3, 2): 8.0}, 0.0, 'BINARY')


<a id="Task2"></a>

### Task 2

Create a QUBO dictionary form for the following objective function and create a BQM from it.

$$f(x_1, x_2, x_3, x_4) = 3x_1 - 7x_2 + 11x_3 - x_4 + 9x_1 x_2 + x_1 x_3 + 2x_2 x_3 + 8x_3 x_4$$

### Solution

Define a QUBO in dictionary form for the given objective function.

In [9]:
Q_dict = {
    ("x1", "x1"): 3,
    ("x2", "x2"): -7,
    ("x3", "x3"): 11,
    ("x4", "x4"): -1,
    ("x1", "x2"): 9,
    ("x1", "x3"): 1,
    ("x2", "x3"): 2,
    ("x3", "x4"): 8,
}

Construct a BQM from the above dictionary `Q_dict`.

In [10]:
bqm_qubo_dict = BQM.from_qubo(Q_dict)

print(bqm_qubo_dict)

BinaryQuadraticModel({'x1': 3.0, 'x2': -7.0, 'x3': 11.0, 'x4': -1.0}, {('x2', 'x1'): 9.0, ('x3', 'x1'): 1.0, ('x3', 'x2'): 2.0, ('x4', 'x3'): 8.0}, 0.0, 'BINARY')


<a id="Task3"></a>


### Task 3

Obtain the $Q$ matrix for the bqm formulation you created in Task 2. 

### Solution

In [12]:
print(bqm_qubo_dict.to_numpy_matrix(["x1", "x2", "x3", "x4"]))

[[ 3.  9.  1.  0.]
 [ 0. -7.  2.  0.]
 [ 0.  0. 11.  8.]
 [ 0.  0.  0. -1.]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: bqm.to_numpy_matrix() is deprecated since dimod 0.10.0 and will be removed in 0.12.0
  """Entry point for launching an IPython kernel.


<a id="Task4"></a>

### Task 4

Obtain the QUBO dictionary for the bqm formulation you created in Task 1. 

### Solution

In [14]:
print(bqm_qubo_np.to_qubo())

({(1, 0): 9.0, (2, 0): 1.0, (2, 1): 2.0, (3, 2): 8.0, (0, 0): 3.0, (1, 1): -7.0, (2, 2): 11.0, (3, 3): -1.0}, 0.0)


<a id="Task5"></a>

### Task 5

Create dictionaries $h$ and $J$ for the following Ising model and obtain bqm model using `from_ising` function.

$$s_1 + s_2 + s_3 + s_4 - 6s_1 s_3 - 6s_1 s_4 - 6s_3 s_4 - 6s_1 s_2.$$

In [16]:
h = {"s1":1, "s2":2, "s3":1, "s4":1}
J = {("s1","s3"):-6, ("s1","s4"):-6, ("s3","s4"):-6, ("s1","s2"):-6}

bqm_ising = BQM.from_ising(h, J)
print(bqm_ising)

BinaryQuadraticModel({'s1': 1.0, 's3': 1.0, 's4': 1.0, 's2': 2.0}, {('s3', 's1'): -6.0, ('s4', 's1'): -6.0, ('s4', 's3'): -6.0, ('s2', 's1'): -6.0}, 0.0, 'SPIN')


<a id="Task6"></a>

### Task 6

Obtain the Ising model for the bqm formulation you created in Task 2. 

Note: BQM formulation you created in Task 2 has variable type `BINARY` and it will be converted into `SPIN` after you make the conversion.

### Solution

In [18]:
print(bqm_qubo_dict.to_ising())

({'x1': 4.0, 'x2': -0.75, 'x3': 8.25, 'x4': 1.5}, {('x2', 'x1'): 2.25, ('x3', 'x1'): 0.25, ('x3', 'x2'): 0.5, ('x4', 'x3'): 2.0}, 8.0)


Note that the coefficients are changed.

In [19]:
print(bqm_qubo_dict)

BinaryQuadraticModel({'x1': 3.0, 'x2': -7.0, 'x3': 11.0, 'x4': -1.0}, {('x2', 'x1'): 9.0, ('x3', 'x1'): 1.0, ('x3', 'x2'): 2.0, ('x4', 'x3'): 8.0}, 0.0, 'BINARY')


<a id="Task7"></a>

### Task 7

Convert the following QUBO formulation into Ising formulation using the `BQM` class.

$$5x_1 + 7x_1 x_2 - 3x_2.$$

Note: Go back to the following [Ising model conversion](Ising_Model_2.ipynb#Task2) notebook to compare your solution.

### Solution

We will first create a BQM instance.

In [21]:
linear = {'x1': 5, 'x2': -3}
quadratic = {('x1', 'x2'): 7}
vartype = 'BINARY'

bqm = BQM(linear, quadratic, vartype)

Next, we convert it into Ising model. 

In [22]:
bqm.to_ising()

({'x1': 4.25, 'x2': 0.25}, {('x2', 'x1'): 1.75}, 2.75)

This is exactly the same Ising model we had obtained in the previous notebook.

$$\frac{17}{4}s_1 + \frac{1}{4}s_2 + \frac{7}{4}s_1s_2 + \frac{11}{4}$$

<a id="Task8"></a>

### Task 8

Convert the following Ising model into QUBO formulation using the `BQM` class.

$$s_1s_2 - s_1 + 3s_2.$$

Note: Go back to the following [Ising model conversion](Ising_Model_2.ipynb#Task3) notebook to compare your solution.

### Solution

We will first create a BQM instance.

In [24]:
h = {'s1': -1, 's2':3}
J = {('s1', 's2'): 1}
vartype = 'SPIN'

bqm = BQM(h, J, vartype)

Next, we convert it into QUBO formulation. 

In [25]:
bqm.to_qubo()

({('s2', 's1'): 4.0, ('s1', 's1'): -4.0, ('s2', 's2'): 4.0}, -1.0)

This is exactly the same QUBO formulation we had obtained in the previous notebook.
$$4x_1x_2 - 4x_1 + 4x_2 - 1$$